export const methods = {
  // vm
  ADD_ARGO_FIREWALL_RULE: 'add_argo_firewall_rule',
  ADD_DISK: 'add_disk',
  ADD_NET_FIREWALL_RULE: 'add_net_firewall_rule',
  ADD_NIC: 'add_nic',
  CREATE_CHILD_SERVICE_VM: 'create_child_service_vm',
  DELETE: 'delete',
  DELETE_ARGO_FIREWALL_RULE: 'delete_argo_firewall_rule',
  DELETE_NET_FIREWALL_RULE: 'delete_net_firewall_rule',
  DESTROY: 'destroy',
  GET_DB_KEY: 'get_db_key',
  GET_DOMSTORE_KEY: 'get_domstore_key',
  HIBERNATE: 'hibernate',
  LIST_ARGO_FIREWALL_RULES: 'list_argo_firewall_rules',
  LIST_DISKS: 'list_disks',
  LIST_NET_FIREWALL_RULES: 'list_net_firewall_rules',
  LIST_NICS: 'list_nics',
  PAUSE: 'pause',
  READ_ICON: 'read_icon',
  REBOOT: 'reboot',
  RESUME: 'resume',
  RESUME_FROM_FILE: 'resume_from_file',
  SET_DB_KEY: 'set_db_key',
  SET_DOMSTORE_KEY: 'set_domstore_key',
  SHUTDOWN: 'shutdown',
  SLEEP: 'sleep',
  START: 'start',
  START_INTERNAL: 'start_internal',
  SUSPEND_TO_FILE: 'suspend_to_file',
  SWITCH: 'switch',
  UNPAUSE: 'unpause',

  // auth
  AUTH: 'auth',
  AUTH_REQUIRED: 'auth_required',

  // pci
  ADD_PT_RULE: 'add_pt_rule',
  ADD_PT_RULE_BDF: 'add_pt_rule_bdf',
  DELETE_PT_RULE: 'delete_pt_rule',
  DELETE_PT_RULE_BDF: 'delete_pt_rule_bdf',
  LIST_PT_PCI_DEVICES: 'list_pt_pci_devices',
  LIST_PT_RULES: 'list_pt_rules',

  // product
  GET_OVF_ENV_XML: 'get_ovf_env_xml',
  GET_PRODUCT_PROPERTY: 'get_product_property',
  LIST_PRODUCT_PROPERTIES: 'list_product_properties',
  SET_PRODUCT_PROPERTY: 'set_product_property',
};
