const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
const SOCKET_CONNECTION_ESTABLISHED = 'SOCKET_CONNECTION_ESTABLISHED';
const SOCKET_CONNECTION_CLOSED = 'SOCKET_CONNECTION_CLOSED';
const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';
const SOCKET_READY = 'SOCKET_READY';

const actions = {
  SOCKET_CONNECTION_ERROR,
  SOCKET_CONNECTION_ESTABLISHED,
  SOCKET_CONNECTION_CLOSED,
  SOCKET_SEND_MESSAGE,
  SOCKET_READY,
  sendMessage: (payload) => ({ type: SOCKET_SEND_MESSAGE, payload }),
};

export default actions;
