const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
const SOCKET_CONNECTION_ESTABLISHED = 'SOCKET_CONNECTION_ESTABLISHED';
const SOCKET_CONNECTION_CLOSED = 'SOCKET_CONNECTION_CLOSED';
const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';

const actions = {
    SOCKET_CONNECTION_ERROR,
    SOCKET_CONNECTION_ESTABLISHED,
    SOCKET_CONNECTION_CLOSED,
    SOCKET_CONNECTION_ESTABLISHED,
    SOCKET_SEND_MESSAGE,
    messageReceived: payload => ({ type: SOCKET_MESSAGE_RECEIVED, payload }),
    sendMessage: payload => ({ type: SOCKET_SEND_MESSAGE, payload }),
}

export default actions;
