export default {
  SOCKET_CONNECTION_READY: 'SOCKET_CONNECTION_READY',
  SOCKET_SEND_MESSAGE: 'SOCKET_SEND_MESSAGE',
  SOCKET_MESSAGE_RECEIVED: 'SOCKET_MESSAGE_RECEIVED',
  SOCKET_MESSAGE_SENT: 'SOCKET_MESSAGE_SENT',
};
