export default {
  VM_PATH_ACQUIRED: 'VM_PATH_ACQUIRED',
  VM_LOADED: 'VM_LOADED',

  VM_PROPERTIES_LOADED: 'VM_PROPERTIES_LOADED',
  VM_LOAD_PROPERTIES: 'VM_LOAD_PROPERTIES',

  VM_LOAD_ARGO_FIREWALL_RULES: 'VM_LOAD_ARGO_FIREWALL_RULES',
  VM_ARGO_FIREWALL_RULES_LOADED: 'VM_ARGO_FIREWALL_RULES_LOADED',

  VM_LOAD_PT_PCI_DEVICES: 'VM_LOAD_PT_PCI_DEVICES',
  VM_PT_PCI_DEVICES_LOADED: 'VM_PT_PCI_DEVICES_LOADED',

  VM_LOAD_PT_RULES: 'VM_LOAD_PT_RULES',
  VM_PT_RULES_LOADED: 'VM_PT_RULES_LOADED',

  VM_LOAD_NET_FIREWALL_RULES: 'VM_LOAD_NET_FIREWALL_RULES',
  VM_NET_FIREWALL_RULES_LOADED: 'VM_NET_FIREWALL_RULES_LOADED',

  VM_LOAD_PRODUCT_PROPERTIES: 'VM_LOAD_PRODUCT_PROPERTIES',
  VM_PRODUCT_PROPERTIES_LOADED: 'VM_PRODUCT_PROPERTIES_LOADED',

  VM_LOAD_NICS: 'VM_LOAD_NICS',
  VM_NIC_LOADED: 'VM_NIC_LOADED',

  VM_LOAD_DISKS: 'VM_LOAD_DISKS',
  VM_DISK_LOADED: 'VM_DISK_LOADED',

  VM_LOAD_PROPERTY: 'VM_LOAD_PROPERTY',
  VM_PROPERTY_LOADED: 'VM_PROPERTY_LOADED',

  VM_REMOVE: 'VM_REMOVE',
  VM_STATE_UPDATED: 'VM_STATE_UPDATED',
};
