export default {
  HOST_LOAD_PROPERTIES: 'HOST_LOAD_PROPERTIES',
  HOST_PROPERTIES_LOADED: 'HOST_PROPERTIES_LOADED',

  HOST_LOAD_SOUND: 'HOST_LOAD_SOUND',
  HOST_SOUND_CAPTURE_DEVICES_LOADED: 'HOST_SOUND_CAPTURE_DEVICES_LOADED',
  HOST_SOUND_PLAYBACK_DEVICES_LOADED: 'HOST_SOUND_PLAYBACK_DEVICES_LOADED',
  HOST_SOUND_CARD_LOADED: 'HOST_SOUND_CARD_LOADED',

  HOST_LOAD_POWER: 'HOST_LOAD_POWER',
  HOST_POWER_LOADED: 'HOST_POWER_LOADED',

  HOST_LOAD_CD_DEVICES: 'HOST_LOAD_CD_DEVICES',
  HOST_CD_DEVICES_LOADED: 'HOST_CD_DEVICES_LOADED',

  HOST_LOAD_PCI_DEVICES: 'HOST_LOAD_PCI_DEVICES',
  HOST_PCI_DEVICES_LOADED: 'HOST_PCI_DEVICES_LOADED',

  HOST_LOAD_GPUS: 'HOST_LOAD_GPUS',
  HOST_GPUS_LOADED: 'HOST_GPUS_LOADED',

  HOST_LOAD_ISOS: 'HOST_LOAD_ISOS',
  HOST_ISOS_LOADED: 'HOST_ISOS_LOADED',

  HOST_LOAD_INSTALL_STATE: 'HOST_LOAD_INSTALL_STATE',
  HOST_INSTALL_STATE_LOADED: 'HOST_INSTALL_STATE_LOADED',

  HOST_LOAD_WALLPAPERS: 'HOST_LOAD_WALLPAPERS',
  HOST_WALLPAPERS_LOADED: 'HOST_WALLPAPERS_LOADED',

  HOST_EULA_LOADED: 'HOST_EULA_LOADED',

  HOST_LOAD_INPUT: 'HOST_LOAD_INPUT',
  HOST_INPUT_LOADED: 'HOST_INPUT_LOADED',

  HOST_LOAD_USB_DEVICES: 'HOST_LOAD_USB_DEVICES',
  HOST_USB_DEVICE_LOADED: 'HOST_USB_DEVICE_LOADED',

  HOST_STATE_UPDATED: 'HOST_STATE_UPDATED',
};
