import * as DBus from '../dbus';
import { services, interfaces } from '../constants';

const signals = {
  AUTH_REMOTE_START_LOGIN: 'auth_remote_start_login',
  AUTH_REMOTE_START_RECOVERY: 'auth_remote_start_recovery',
  AUTH_STATUS: 'auth_status',
  FOCUS_AUTH_FIELD: 'focus_auth_field',
  KEYBOARD_FOCUS_CHANGE: 'keyboard_focus_change',
  LID_STATE_CHANGED: 'lid_state_changed',
  SECURE_MODE: 'secure_mode',
  SYNC_AUTH_USERNAME: 'sync_auth_username',
};

export default {
  signals,
  attachVkbd: (domId: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'attach_vkbd',
    domId,
  ),
  authBegin: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_begin',
  ),
  authClearStatus: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_clear_status',
  ),
  authCollectPassword: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_collect_password',
  ),
  authCreateHash: (fname: string, password: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_create_hash',
    fname, password,
  ),
  authGetContext: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_get_context',
  ),
  authGetStatus: (clear: boolean): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_get_status',
    clear,
  ),
  authRemoteLogin: (username: string, password: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_remote_login',
    username, password,
  ),
  authRemoteStatus: (autoStarted: boolean, status: number, id: string, username: string,
    recoveryKeyFile: string, ctxFlags: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_remote_status',
    autoStarted, status, id, username, recoveryKeyFile, ctxFlags,
  ),
  authRmPlatformUser: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_rm_platform_user',
  ),
  authSetContext: (user: string, title: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_set_context',
    user, title,
  ),
  authSetContextFlags: (
    user: string,
    title: string,
    flags: string,
  ): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_set_context_flags',
    user, title, flags,
  ),
  authTitle: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'auth_title',
  ),
  detachVkbd: (domId: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'detach_vkbd',
    domId,
  ),
  divertKeyboardFocus: (uuid: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'divert_keyboard_focus',
    uuid,
  ),
  divertMouseFocus: (uuid: string, sX1: number, sY1: number, sX2: number, sY2: number, dX1: number,
    dY1: number, dX2: number, dY2: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'divert_mouse_focus',
    uuid, sX1, sY1, sX2, sY2, dX1, dY1, dX2, dY2,
  ),
  focusMode: (mode: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'focus_mode',
    mode,
  ),
  getAuthOnBoot: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_auth_on_boot',
  ),
  getCurrentKbLayout: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_current_kb_layout',
  ),
  getFocusDomid: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_focus_domid',
  ),
  getIdleTime: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_idle_time',
  ),
  getKbLayouts: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_kb_layouts',
  ),
  getLastInputTime: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_last_input_time',
  ),
  getLidState: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_lid_state',
  ),
  getMouseSpeed: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_mouse_speed',
  ),
  getPlatformUser: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_platform_user',
  ),
  getRemoteUserHash: (userId: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_remote_user_hash',
    userId,
  ),
  getUserKeydir: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'get_user_keydir',
  ),
  lock: (canSwitchOut: boolean): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'lock',
    canSwitchOut,
  ),
  lockTimeoutGet: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'lock_timeout_get',
  ),
  lockTimeoutSet: (value: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'lock_timeout_set',
    value,
  ),
  setAuthOnBoot: (auth: boolean): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'set_auth_on_boot',
    auth,
  ),
  setCurrentKbLayout: (layout: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'set_current_kb_layout',
    layout,
  ),
  setDivertKeyboardFilter: (...keyFilter: number[]): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'set_divert_keyboard_filter',
    ...keyFilter,
  ),
  setMouseSpeed: (mouseSpeed: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'set_mouse_speed',
    mouseSpeed,
  ),
  setSlot: (domId: number, slot: number): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'set_slot',
    domId, slot,
  ),
  stopKeyboardDivert: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'stop_keyboard_divert',
  ),
  stopMouseDivert: (): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'stop_mouse_divert',
  ),
  switchFocus: (domId: number, force: boolean): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'switch_focus',
    domId, force,
  ),
  touch: (uuid: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'touch',
    uuid,
  ),
  touchpadGet: (name: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'touchpad_get',
    name,
  ),
  touchpadSet: (name: string, value: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'touchpad_set',
    name, value,
  ),
  updateSeamlessMouseSettings: (domUuid: string): Promise<DBus.Arguments> => DBus.send(
    services.INPUT,
    '/',
    interfaces.INPUT,
    'update_seamless_mouse_settings',
    domUuid,
  ),
};
