import { interfaces, services } from '../constants';
import { buildMessage } from '../dbus';

export const methods = {
  ADD_RULE: 'add_rule',
  ADD_VAR: 'add_var',
  AGGREGATE_BATTERY_PERCENTAGE: 'aggregate_battery_percentage',
  AGGREGATE_BATTERY_STATE: 'aggregate_battery_state',
  AGGREGATE_BATTERY_TIME_TO_EMPTY: 'aggregate_battery_time_to_empty',
  AGGREGATE_BATTERY_TIME_TO_FULL: 'aggregate_battery_time_to_full',
  BATTERIES_PRESENT: 'batteries_present',
  BATTERY_IS_PRESENT: 'battery_is_present',
  BATTERY_PERCENTAGE: 'battery_percentage',
  BATTERY_STATE: 'battery_state',
  BATTERY_TIME_TO_EMPTY: 'battery_time_to_empty',
  BATTERY_TIME_TO_FULL: 'battery_time_to_full',
  CLEAR_POLICY: 'clear_policy',
  CLEAR_RULES: 'clear_rules',
  CLEAR_VARS: 'clear_vars',
  GET_AC_ADAPTER_STATE: 'get_ac_adapter_state',
  GET_ACTIONS: 'get_actions',
  GET_BIF: 'get_bif',
  GET_BST: 'get_bst',
  GET_CONDITIONS: 'get_conditions',
  GET_CRITICAL_TEMPERATURE: 'get_critical_temperature',
  GET_CURRENT_BATTERY_LEVEL: 'get_current_battery_level',
  GET_CURRENT_TEMPERATURE: 'get_current_temperature',
  GET_RULES: 'get_rules',
  GET_VARS: 'get_vars',
  HOTKEY_SWITCH: 'hotkey_switch',
  INDICATE_INPUT: 'indicate_input',
  LOAD_POLICY_FROM_DB: 'load_policy_from_db',
  LOAD_POLICY_FROM_FILE: 'load_policy_from_file',
  REMOVE_RULE: 'remove_rule',
  REMOVE_VAR: 'remove_var',
};

const path = '/';

const xcpmd = (method, ...args) => buildMessage(
  services.XCPMD,
  path,
  interfaces.XCPMD,
  method,
  ...args,
);

export default {
  addRule: (name, conditions, actions, undoActions) => xcpmd(
    methods.ADD_RULE,
    name, conditions, actions, undoActions,
  ),
  addVar: (name, value) => xcpmd(methods.ADD_VAR, name, value),
  aggregateBatteryPercentage: () => xcpmd(methods.AGGREGATE_BATTERY_PERCENTAGE),
  aggregateBatteryState: () => xcpmd(methods.AGGREGATE_BATTERY_STATE),
  aggregateBatteryTimeToEmpty: () => xcpmd(methods.AGGREGATE_BATTERY_TIME_TO_EMPTY),
  aggregateBatteryTimeToFull: () => xcpmd(methods.AGGREGATE_BATTERY_TIME_TO_FULL),
  batteriesPresent: () => xcpmd(methods.BATTERIES_PRESENT),
  batteryIsPresent: (batteryId) => xcpmd(methods.BATTERY_IS_PRESENT, batteryId),
  batteryPercentage: (batteryId) => xcpmd(methods.BATTERY_PERCENTAGE, batteryId),
  batteryState: (batteryId) => xcpmd(methods.BATTERY_STATE, batteryId),
  batteryTimeToEmpty: (batteryId) => xcpmd(methods.BATTERY_TIME_TO_EMPTY, batteryId),
  batteryTimeToFull: (batteryId) => xcpmd(methods.BATTERY_TIME_TO_FULL, batteryId),
  clearPolicy: () => xcpmd(methods.CLEAR_POLICY),
  clearRules: () => xcpmd(methods.CLEAR_RULES),
  clearVars: () => xcpmd(methods.CLEAR_VARS),
  getAcAdapterState: () => xcpmd(methods.GET_AC_ADAPTER_STATE),
  getActions: () => xcpmd(methods.GET_ACTIONS),
  getBif: () => xcpmd(methods.GET_BIF),
  getBst: () => xcpmd(methods.GET_BST),
  getConditions: () => xcpmd(methods.GET_CONDITIONS),
  getCriticalTemperature: () => xcpmd(methods.GET_CRITICAL_TEMPERATURE),
  getCurrentBatteryLevel: () => xcpmd(methods.GET_CURRENT_BATTERY_LEVEL),
  getCurrentTemperature: () => xcpmd(methods.GET_CURRENT_TEMPERATURE),
  getRules: () => xcpmd(methods.GET_RULES),
  getVars: () => xcpmd(methods.GET_VARS),
  hotkeySwitch: (reset) => xcpmd(methods.HOTKEY_SWITCH, reset),
  indicateInput: (inputValue) => xcpmd(methods.INDICATE_INPUT, inputValue),
  loadPolicyFromDb: () => xcpmd(methods.LOAD_POLICY_FROM_DB),
  loadPolicyFromFile: (filename) => xcpmd(methods.LOAD_POLICY_FROM_FILE, filename),
  removeRule: (name) => xcpmd(methods.REMOVE_RULE, name),
  removeVar: (name) => xcpmd(methods.REMOVE_VAR, name),
};
