import * as DBus from '../dbus';
import { services, interfaces } from '../constants';

const signals = {
  AC_ADAPTER_STATE_CHANGED: 'ac_adapter_state_changed',
  BATTERY_INFO_CHANGED: 'battery_info_changed',
  BATTERY_LEVEL_NOTIFICATION: 'battery_level_notification',
  BATTERY_STATUS_CHANGED: 'battery_status_changed',
  BCL_KEY_PRESSED: 'bcl_key_pressed',
  NUM_BATTERIES_CHANGED: 'num_batteries_changed',
  OEM_EVENT_TRIGGERED: 'oem_event_triggered',
  POWER_BUTTON_PRESSED: 'power_button_pressed',
  SLEEP_BUTTON_PRESSED: 'sleep_button_pressed',
};

export default {
  signals,
  addRule: (name: string, conditions: string, actions: string,
    undoActions: string): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'add_rule',
    name, conditions, actions, undoActions,
  ),
  addVar: (name: string, value: string): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'add_var',
    name, value,
  ),
  aggregateBatteryPercentage: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'aggregate_battery_percentage',
  ),
  aggregateBatteryState: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'aggregate_battery_state',
  ),
  aggregateBatteryTimeToEmpty: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'aggregate_battery_time_to_empty',
  ),
  aggregateBatteryTimeToFull: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'aggregate_battery_time_to_full',
  ),
  batteriesPresent: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'batteries_present',
  ),
  batteryIsPresent: (battery: number): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'battery_is_present',
    battery,
  ),
  batteryPercentage: (battery: number): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'battery_percentage',
    battery,
  ),
  batteryState: (battery: number): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'battery_state',
    battery,
  ),
  batteryTimeToEmpty: (battery: number): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'battery_time_to_empty',
    battery,
  ),
  batteryTimeToFull: (battery: number): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'battery_time_to_full',
    battery,
  ),
  clearPolicy: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'clear_policy',
  ),
  clearRules: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'clear_rules',
  ),
  clearVars: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'clear_vars',
  ),
  getAcAdapterState: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_ac_adapter_state',
  ),
  getActions: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_actions',
  ),
  getBif: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_bif',
  ),
  getBst: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_bst',
  ),
  getConditions: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_conditions',
  ),
  getCriticalTemperature: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_critical_temperature',
  ),
  getCurrentBatteryLevel: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_current_battery_level',
  ),
  getCurrentTemperature: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_current_temperature',
  ),
  getRules: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_rules',
  ),
  getVars: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'get_vars',
  ),
  hotkeySwitch: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'hotkey_switch',
  ),
  indicateInput: (inputValue: number): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'indicate_input',
    inputValue,
  ),
  loadPolicyFromDb: (): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'load_policy_from_db',
  ),
  loadPolicyFromFile: (fileName: string): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'load_policy_from_file',
    fileName,
  ),
  removeRule: (ruleName: string): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'remove_rule',
    ruleName,
  ),
  removeVar: (name: string): Promise<DBus.Arguments> => DBus.send(
    services.XCPMD,
    '/',
    interfaces.XCPMD,
    'remove_var',
    name,
  ),
};
