export default {
  NDVM_REMOVE: 'NDVM_REMOVE',

  NDVM_LOAD_NETWORKS: 'NDVM_LOAD_NETWORKS',
  NDVM_NETWORK_LOADED: 'NDVM_NETWORK_LOADED',

  NDVM_LOAD_PROPERTIES: 'NDVM_LOAD_PROPERTIES',
  NDVM_PROPERTIES_LOADED: 'NDVM_PROPERTIES_LOADED',
};
