export default {
  // response types
  DBUS_SIGNAL_RECEIVED: 'DBUS_SIGNAL_RECEIVED',
  DBUS_ERROR_RECEIVED: 'DBUS_ERROR_RECEIVED',
  DBUS_CONNECTION_ERROR: 'DBUS_CONNECTION_ERROR',
  DBUS_CONNECTION_ESTABLISHED: 'DBUS_CONNECTION_ESTABLISHED',
  DBUS_SIGNALS_REGISTERED: 'DBUS_SIGNALS_REGISTERED',
};
